name: Test changelog files

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: password
    strategy:
      matrix:
        liquibase-version:
          - "liquibase/liquibase:4.25"
          # - "liquibase/liquibase:4.26"
          # - "liquibase:4.27"
          # - "liquibase:4.28"
          # - "liquibase:4.29"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify changelog
        uses: ${{ matrix.liquibase-version }}
        run: |
          liquibase \
            --changeLogFile=app/changelog-master.yaml \
            --url="jdbc:mariadb://db:3306" \
            --username=root \
            --password=password \
            update-sql
